name: Publish to GHCR

on:
  push:

jobs:
  build:
    name: Build and publish to GHCR
    if: github.repository == 'pagefaultgames/rogueserver'
    env:
      GO_VERSION: 1.22
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            VERSION=${{ github.ref_name }}-SNAPSHOT
            COMMIT_SHA=${{ env.GITHUB_SHA_SHORT }}
